# Generated by Django 5.2.17 on 2026-08-08 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.TextField(blank=True, default='')),
                ('destination', models.TextField(blank=True, default='')),
                ('driver_name', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle', models.CharField(blank=True, default='', max_length=150)),
                ('tracking_number', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Ready for Pickup', 'Ready for Pickup'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Confirmed', 'Confirmed')], default='Pending', max_length=30)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_shipments', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.wastelisting')),
                ('logistics_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipments', to=settings.AUTH_USER_MODEL)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_shipments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='core.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
