# Generated by Django 5.2.17 on 2026-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelisting',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastelisting',
            name='ai_ewc_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastelisting',
            name='ai_material_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
