# Generated by Django 5.2.17 on 2026-08-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wastelisting_ai_confidence_wastelisting_ai_ewc_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProductPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpp_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('material_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('condition', models.CharField(blank=True, max_length=50)),
                ('ai_classification', models.CharField(blank=True, max_length=100)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('origin_governorate', models.CharField(blank=True, max_length=255)),
                ('destination_governorate', models.CharField(blank=True, max_length=255)),
                ('transaction_id_ref', models.IntegerField(blank=True, null=True)),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deal_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=60)),
                ('logistics_partner', models.CharField(blank=True, default='Eco Link Logistics Partner', max_length=255)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('shipment_status', models.CharField(blank=True, max_length=30)),
                ('carbon_info', models.TextField(blank=True, default='')),
                ('recycling_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpp', to='core.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
