# Generated by Django 5.2.17 on 2026-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_digital_product_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supported_materials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
